blueprint:
  name: "Sync Inovelli Blue Light and Fan Switches (ZHA)"
  description: Create automations to syncronize the Inovelli Blue with the state of another entity in HA. 
  domain: automation
  input:
    fan_control:
      name: Toggle to turn the fan function off for when away or seasonally
      description: >
        (#1) ```input_boolean``` - If this is set to off, the Automation
        will be disabled.

        This Helper has to be set up in [![Open your Home Assistant instance and show
        your helper entities.](https://my.home-assistant.io/badges/helpers.svg)](https://my.home-assistant.io/redirect/helpers/)
      selector:
        entity:
          filter:
            - domain: input_boolean
          multiple: false
mode: queued
max_exceeded: silent
# variables:
#   device_id: !input "inovelli_switch"
trigger:
  - platform: event
    event_type: zha_event
condition: "{{ trigger.event.data.device_id == device_id }}"
action:
  - variables:
      command: '{{ trigger.event.data.command }}'
  - service: "logbook.log"
    data:
      name: 'ZHA'
      message: 'received event: {{ command }}'
  